In [8]:
import pandas as pd 
import sqlite3
conn = sqlite3.connect("../data/processed/cosmere.db")

def sql_query(query):
    
    result = pd.read_sql_query(query, conn)
   
    return result

In [ ]:
# Average rating and total ratings per series
# sorted by highest rated

sql_query("""SELECT series, ROUND(AVG(rating), 2) average_rating, SUM(ratings_count) total_ratings_count_per_series
FROM books 
GROUP BY series
ORDER BY average_rating DESC""")

               series  average_rating  total_ratings_count_per_series
0  Stormlight Archive            4.56                            9496
1      Mistborn Era 1            4.46                            9731
2          Standalone            4.38                            4053
3      Mistborn Era 2            4.28                            5106
4          Warbreaker            4.20                            1639
5            Elantris            3.77                            2103

In [ ]:
# Books which are the best and worst performers in each series

sql_query("""
SELECT title, series, rating, ROW_NUMBER() OVER (PARTITION BY series ORDER BY rating DESC) as ranking_by_series
FROM books""")

,title,series,rating,ranking_by_series
0,Elantris,Elantris,4.0661,1
1,The Hope of Elantris,Elantris,3.4794,2
2,The Hero of Ages,Mistborn Era 1,4.5641,1
3,Mistborn: The Final Empire,Mistborn Era 1,4.4689,2
4,The Well of Ascension,Mistborn Era 1,4.3391,3
5,The Lost Metal,Mistborn Era 2,4.4460,1
6,The Bands of Mourning,Mistborn Era 2,4.3603,2
7,Shadows of Self,Mistborn Era 2,4.2059,3
8,The Alloy of Law,Mistborn Era 2,4.1172,4
9,Yumi and the Nightmare Painter,Standalone,4.4505,1
10,Tress of the Emerald Sea,Standalone,4.4218,2
11,The Emperor's Soul,Standalone,4.3829,3
12,The Sunlit Man,Standalone,4.2692,4
13,Words of Radiance,Stormlight Archive,4.7148,1
14,The Way of Kings,Stormlight Archive,4.6337,2
15,Oathbringer,Stormlight Archive,4.5739,3
16,Rhythm of War,Stormlight Archive,4.5399,4
17,Wind and Truth,Stormlight Archive,4.3472,5
18,Warbreaker,Warbreaker,4.1986,1

In [ ]:
# best performing book in each series

sql_query("""WITH best_performer AS (
SELECT title, series, rating, ROW_NUMBER() OVER (PARTITION BY series ORDER BY rating DESC) as ranking_by_series
FROM books)
SELECT title, series, rating
FROM best_performer
WHERE ranking_by_series = 1""")

                            title              series  rating
0                        Elantris            Elantris  4.0661
1                The Hero of Ages      Mistborn Era 1  4.5641
2                  The Lost Metal      Mistborn Era 2  4.4460
3  Yumi and the Nightmare Painter          Standalone  4.4505
4               Words of Radiance  Stormlight Archive  4.7148
5                      Warbreaker          Warbreaker  4.1986